CREATE TABLE ARTIST (
  MBID varchar(100) NOT NULL PRIMARY KEY,
  NAME varchar(1000) NOT NULL,
  DESCRIPTION varchar(10000) NULL,
  LAST_UPDATE TIMESTAMP WITH TIME ZONE NOT NULL,
  IS_INFO_COMPLETE boolean DEFAULT FALSE
);

CREATE TABLE ARTIST_INFO_SOURCE (
  MBID varchar(100) NOT NULL PRIMARY KEY,
  ARTIST_MBID varchar(100) references ARTIST(MBID),
  TYPE varchar(250) NOT NULL,
  RESOURCE varchar(1000) NOT NULL
);

CREATE INDEX idx_fk_artist_info_source_artist ON ARTIST_INFO_SOURCE (ARTIST_MBID);


CREATE TABLE RELEASE_GROUP (
  MBID varchar(100) NOT NULL PRIMARY KEY,
  ARTIST_MBID varchar(100) references ARTIST(MBID),
  TITLE varchar(1000) NOT NULL,
  IMAGE_RESOURCE varchar(1000) NULL
);

CREATE INDEX idx_fk_release_group_artist ON RELEASE_GROUP (ARTIST_MBID);